### ISSUE TITLE
shared memory size at docker run time

### ISSUE THREAD

**Issue by FabianIsensee** [lab-midas/autoPET#10]
Hi there,
how large is the shared memory size going to be when the dockers are evaluated on challenge.org? As it currently stands, my model refuses to run using the run command from [test.sh](https://github.com/lab-midas/autoPET/blob/master/nnUNet_baseline/test.sh)

```
docker run -it --rm \
        --memory="${MEM_LIMIT}" \
        --memory-swap="${MEM_LIMIT}" \
        --network="none" \
        --cap-drop="ALL" \
        --security-opt="no-new-privileges" \
        --shm-size="128m" \
        --pids-limit="256" \
        --gpus="all" \
        -v $SCRIPTPATH/test/input/:/input/ \
        -v autopet_baseline-output-$VOLUME_SUFFIX:/output/ \
        autopet_baseline
```

The reason for this is `--shm-size="128m" \`. Increasing that to `--shm-size="1g" \` fixes the problem. What will this setting be when we submit it to the leaderboard?
Best,
Fabian

**Comment by thomaskuestner** [comment]
Hi Fabian,

the specs of the hardware on grand-challenge is specified here: [https://autopet-ii.grand-challenge.org/submission/](https://autopet-ii.grand-challenge.org/submission/)
It will have 30GB of memory and is running on a GPU with 16GB VRAM.
If you still have trouble with that, we need to check with GC admins why this is the case. 

Kind regards
Thomas

**Comment by FabianIsensee** [comment]
Hey Thomas,
this is not the source of my troubles :-) I am exceeding the shared memory, not the maximum amount of RAM. The shared memory is defined by `--shm-size="128m" \` and is limited (for whatever reason) to 128MB
Best,
Fabian

**Comment by thomaskuestner** [comment]
Hi Fabian,

ok I guess in that case you better speak directly with GC admins: support@grand-challenge.org
as this is nothing what we can solve.

Kind regards
Thomas
