### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Graitristic** [lab-midas/autoPET#11]
Hi,I have some questions about the FDG-PET-CT-lesions.I want to use it,but I have emailed it for a week,there is no answer.So I want to know how long did you spand for applying the dataset.

**Comment by thomaskuestner** [comment]
I am currently out of office. You can download the training data immediately at TCIA: 
https://wiki.cancerimagingarchive.net/plugins/servlet/mobile?contentId=93258287#content/view/93258287

Have fun working with the database!
