### ISSUE TITLE
Question regarding running predictions on new data

### ISSUE THREAD

**Issue by vikashg** [lab-midas/autoPET#13]
Hi, 
I am trying to test and the `nnUNet_baseline` on some local data. When I run the `test.sh` in the `nnUNet_baseline` folder. After your suggestion with the `git lfs pull` I am able to run it comfortably. 
However I have following 2 questions 
1. In the `Dockerfile` 
`ENTRYPOINT python -m process $0 $@` What does the `$0` and `$@` does ? I tried to find an answer but was not clear to me. 

2. I would like to see how the basemodel performs on my data. Do I need to just copy my data in appropriate folder in the `autoPET/test/input` folder and then run the `autopet_baseline` docker container?

Please advice
Thanks a lot.

**Comment by thomaskuestner** [comment]
1. This just hands over the script name ($0) and all parameters ($@) to the Python script. In our case this is not needed.
2. You can either replace the test/input samples, but the code runs through only one sample per call. You would either need to create your own loop around or alternatively just use the normal nnUNet framework for running the inferences, please refer to the documentation here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format_inference.md

**Comment by vikashg** [comment]
Thank you. When I am done working with it. I can create a pull request, if you want.

**Comment by thomaskuestner** [comment]
Thanks
