### ISSUE TITLE
LFS bandwidth

### ISSUE THREAD

**Issue by ctwayen** [lab-midas/autoPET#2]
Hi when I try to use git lfs download the weights, the error "batch response: This repository is over its data quota. Account responsible forLFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/lab-midas/autoPET.git/inf/lfs' 
" was raised. Are there any other links to download the weight

**Comment by thomaskuestner** [comment]
We are sorry to hear that. There are no other download links for the weights, but maybe you can give it another go in a few days.
