### ISSUE TITLE
Unpickling error while running  run_inference function

### ISSUE THREAD

**Issue by Mehulk08** [lab-midas/autoPET#6]
starting
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
[<ipython-input-7-eed488b37fae>](https://localhost:8080/#) in <module>()
    138 
    139 if __name__ == '__main__':
--> 140     run_inference()
    141 

5 frames
[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    918             "functionality.")
    919 
--> 920     magic_number = pickle_module.load(f, **pickle_load_args)
    921     if magic_number != MAGIC_NUMBER:
    922         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, 'v'.

**Comment by thomaskuestner** [comment]
Can you please provide some more information?
In case you are trying to run the inference on the provided data samples in the repository, did you ensure that the GIT LFS files were correctly downloaded?

**Comment by thomaskuestner** [comment]
Closing it, please reopen if the problem still persists.
