### ISSUE TITLE
annotation protocol 

### ISSUE THREAD

**Issue by JunMa11** [lab-midas/autoPET#8]
Dear organizers,

> grand-challenge forum cannot directly upload images, so I post the question here

I found the following annotation protocol in the challenge document
- Step 1: Identification of FDG-avid tumor lesions by visual assessment of PET and CT information together with the clinical examination reports.
- Step 2: Manual free-hand segmentation of identified lesions in axial slices

Would it be possible to provide more details on the annotation protocol? E.g., how the radiologists identify the lesions from PET and CT, and how do they avoid FP and FN based on the images?

I go through the training images and it seems that most lesions have high intensity in PET.
However, the case `PETCT_1b199d094d-0.nii.gz` does not match the feature. Is this a label error?

![WeChat Image_20220822221559](https://user-images.githubusercontent.com/19947331/186054152-dc68bf44-82dd-47fd-8cd9-b5103df00706.png)

**Comment by sergiosgatidis** [comment]
Thank you for your question! This is indeed a more challenging case with liver metastases that have relatively low tracer uptake compared to the liver background. Still, these are metastases and should - in principle - be identified. Admittedly, this case might be challenging even for human experts.
<img width="711" alt="image" src="https://user-images.githubusercontent.com/52936169/186105258-8d203955-e402-4bf0-95a3-cee5bb0b4bb3.png">

**Comment by JunMa11** [comment]
Hi @sergiosgatidis ,

Thanks for your answer very much.

Would it be possible to provide more details on the annotation protocol? E.g., how do the radiologists identify the lesions from PET and CT, and how do they avoid FP and FN based on the images?

**Comment by sergiosgatidis** [comment]
The annotation process relies on many years of experience in clinical hybrid imaging combined with relevant clinical knowledge. We will soon publish a technical paper describing the dataset and the annotation process in detail. Once published we will post it on the TCIA page.

**Comment by JunMa11** [comment]
Hi @sergiosgatidis ,

Would it be possible for you to share some general protocols? how do the radiologists identify the lesions from PET and CT, and how do they avoid FP and FN based on the images?

Since the testing submission deadline is very close, this information is very important for us to select postprocessing strategies.

**Comment by sergiosgatidis** [comment]
A very good source that describes this process can be found here: https://cancerimagingjournal.biomedcentral.com/articles/10.1186/s40644-016-0091-3

**Comment by JunMa11** [comment]
Awesome!
Thanks:)
